# Configuration file for codecov reporting code coverage

codecov:
  token: 6cba80e7-6201-4ee5-baf2-b44b290ad103
  status:
    project:
      default:
        # base on last build, but allow drop of upto this percent
        threshold: 0.5%
