name: NeuNorm
channels:
  - conda-forge
dependencies:
  # base
  - python
  - versioningit
  - toml
  # compute
  - astropy
  - numpy
  - scipy
  - ipython
  - h5py
  # visualization
  - pillow
  # utils
  - tqdm
  - pre-commit
  # conda packaging
  - anaconda-client  # for uploading to anaconda
  - boa
  - conda-build
  - conda-verify
  - python-build
  # tests
  - pytest
  # doc
  - sphinx
  - sphinx_rtd_theme
  - nbsphinx
  # pip
  - pip
