[project]
name = "NeuNorm"
description = "neutron normalization data"
long-description = "See the README.md file on GitHub for more information"
keywords = ["neutron", "normalization", "imaging"]
dynamic = ["version"]
requires-python = ">=3.10"
dependencies = [
  "numpy",
  "pillow",
  "pathlib",
  "astropy",
  "scipy",
]
license = { text = "BSD-3-Clause license" }
authors = [
  { name = "Jean Bilheux", email = "bilheuxjm@ornl.gov"},
]
maintainers = [
  { name = "Jean Bilheux", email = "bilheuxjm@ornl.gov"},
  { name = "Chen Zhang", email="zhangc@ornl.gov"},
]

[project.urls]
homepage = "https://github.com/neutrons/python_project_template/"  # if no homepage, use repo url

[build-system]
requires = [
  "setuptools >= 40.6.0",
  "wheel",
  "toml",
  "versioningit"
]
build-backend = "setuptools.build_meta"

[tool.black]
line-length = 119

[tool.versioningit.vcs]
method = "git"
default-tag = "0.0.1"

[tool.versioningit.next-version]
method = "minor"

[tool.versioningit.format]
distance = "{next_version}.dev{distance}"
dirty = "{version}+d{build_date:%Y%m%d}"
distance-dirty = "{next_version}.dev{distance}+d{build_date:%Y%m%d%H%M}"

[tool.versioningit.write]
file = "src/NeuNorm/_version.py"

[tool.setuptools.packages.find]
where = ["src"]
exclude = ["tests*", "scripts*", "docs*", "notebooks*"]

[tool.setuptools.package-data]
"*" = ["*.yml","*.yaml","*.ini"]

[tool.pytest.ini_options]
pythonpath = [
  ".", "src", "scripts"
]
testpaths = ["tests"]
python_files = ["test*.py"]
norecursedirs = [".git", "tmp*", "_tmp*", "__pycache__", "*dataset*", "*data_set*"]

[tool.pylint]
max-line-length = 120
disable = ["too-many-locals",
           "too-many-statements",
           "too-many-instance-attributes",
           "too-many-arguments",
           "duplicate-code"
]

# Add additional 3rd party tool configuration here as needed