"""Signature-guard tests for the released public entry points (#195, Task 2).

These pin the **positional** parameter order of every pipeline and of ``write_tiff_stack`` against
the last release, so a future parameter cannot be inserted mid-signature and silently re-bind every
argument after it.

That is not hypothetical. Commit 3bd2b07 (on ``next``, in no tag) inserted ``rebin_reduction``
immediately after ``rebin_by_tof`` in the three VENUS TOF pipelines and appended
``tiff_one_file_per_image``, shifting every later positional parameter — five of them in
``venus_tpx3_event``. ``write_tiff_stack`` likewise gained two positional parameters. Because none of
that had shipped, the fix was to make all four **keyword-only** rather than freeze the shift; these
guards now pin the v2.2.3 order and assert that everything added since is keyword-only.

**The expected lists below come from git tag v2.2.3, not from the code under test.** That matters: an
earlier version of this file was generated by introspecting the current signatures, so it pinned the
already-shifted order as "released" and could never have failed on the very regression it documents.
Regenerate these lists from the newest tag when a release happens, never from ``next``:

    git show v2.2.3:src/neunorm/pipelines/venus_tpx1.py

Appending a **keyword-only** parameter is always safe and needs no change here. Adding a positional
one, reordering, removing, or converting a released parameter to positional-only is a breaking change:
if a test fails, either revert it or treat it as a deliberate API break with a CHANGELOG entry.

Pattern follows ``test_rebin_tof_flexible.py::test_rebin_tof_preserves_legacy_positional_signature``,
which guards the leaf ``rebin_tof`` the same way.
"""

import inspect

import pytest

from neunorm.exporters.tiff_writer import write_tiff_stack
from neunorm.loaders.metadata_loader import load_metadata
from neunorm.pipelines.mars_ccd import run_mars_ccd_pipeline
from neunorm.pipelines.mars_tpx3 import run_mars_tpx3_pipeline
from neunorm.pipelines.venus_ccd import run_venus_ccd_pipeline
from neunorm.pipelines.venus_tpx1 import run_venus_tpx1_pipeline
from neunorm.pipelines.venus_tpx3_event import run_venus_tpx3_event_pipeline
from neunorm.pipelines.venus_tpx3_histogram import run_venus_tpx3_histogram_pipeline

# Positional order as released in v2.2.3. Sourced from the tag, NOT from the current code.
_VENUS_HISTOGRAM_V223 = [
    "sample_hdf5_paths",
    "ob_hdf5_paths",
    "sample_tiff_paths",
    "ob_tiff_paths",
    "output_path",
    "roi",
    "air_roi",
    "rebin_by_tof",
    "rebin_by_spatial",
    "flight_path",
]

RELEASED_POSITIONAL = {
    "run_venus_tpx1_pipeline": (run_venus_tpx1_pipeline, _VENUS_HISTOGRAM_V223),
    "run_venus_tpx3_histogram_pipeline": (run_venus_tpx3_histogram_pipeline, _VENUS_HISTOGRAM_V223),
    "run_venus_tpx3_event_pipeline": (
        run_venus_tpx3_event_pipeline,
        [
            "sample_paths",
            "ob_paths",
            "binning",
            "output_path",
            "roi",
            "air_roi",
            "rebin_by_tof",
            "rebin_by_spatial",
            "detector_shape",
            "event_id_offset",
            "bank_name",
            "flight_path",
        ],
    ),
    "run_venus_ccd_pipeline": (
        run_venus_ccd_pipeline,
        [
            "sample_paths",
            "ob_paths",
            "dark_paths",
            "output_path",
            "roi",
            "gamma_filter",
            "air_roi",
            "background_roi",
        ],
    ),
    "run_mars_ccd_pipeline": (
        run_mars_ccd_pipeline,
        [
            "sample_paths",
            "ob_paths",
            "dark_paths",
            "output_path",
            "roi",
            "gamma_filter",
            "background_roi",
        ],
    ),
    "run_mars_tpx3_pipeline": (
        run_mars_tpx3_pipeline,
        [
            "sample_paths",
            "ob_paths",
            "output_path",
            "roi",
            "gamma_filter",
            "detector_shape",
            "background_roi",
        ],
    ),
    "write_tiff_stack": (
        write_tiff_stack,
        ["output_path", "transmission", "metadata", "daqmetadata"],
    ),
    # Not a pipeline, but a released public entry point: neunorm.loaders.metadata_loader is
    # published in docs/api.rst with :members:. It gained `image_dir` since v2.2.3, which is now
    # keyword-only for the same reason as the four above.
    "load_metadata": (
        load_metadata,
        ["file_path", "read_shutter_counts", "read_spectra_tof"],
    ),
}


@pytest.mark.parametrize("name", sorted(RELEASED_POSITIONAL))
def test_positional_signature_matches_the_last_release_exactly(name):
    """The positional parameters must equal the v2.2.3 list — same names, same order, nothing extra.

    A full-list comparison, not a prefix: pinning only a prefix would miss a positional parameter
    appended after it, which still shifts nothing today but silently becomes load-bearing order the
    moment another is added. Anything new belongs after a ``*`` marker, where it never appears here.
    """
    func, expected = RELEASED_POSITIONAL[name]
    params = inspect.signature(func).parameters
    actual = [n for n, p in params.items() if p.kind is not p.KEYWORD_ONLY]

    assert actual == expected, (
        f"{name}: positional signature no longer matches the v2.2.3 release.\n"
        f"  released: {expected}\n"
        f"  current:  {actual}\n"
        "Add new parameters as keyword-only (after a `*` marker) instead of positionally."
    )


@pytest.mark.parametrize("name", sorted(RELEASED_POSITIONAL))
def test_released_parameters_remain_callable_by_keyword(name):
    """Every released parameter must still be bindable by name.

    Checks the parameter *kind*, not just the name: converting ``f(a, b)`` to ``f(a, /, b)`` keeps
    both names and both positions, passes an order comparison, and yet breaks every ``f(a=...)``
    caller. Making a released parameter keyword-only would equally break positional callers, and is
    caught by the order test above.
    """
    func, expected = RELEASED_POSITIONAL[name]
    params = inspect.signature(func).parameters

    missing = [n for n in expected if n not in params]
    assert not missing, f"{name}: released parameter(s) removed: {missing}"

    wrong_kind = {
        n: params[n].kind.description for n in expected if params[n].kind is not params[n].POSITIONAL_OR_KEYWORD
    }
    assert not wrong_kind, (
        f"{name}: released parameter(s) are no longer positional-or-keyword: {wrong_kind}. "
        "Positional-only breaks keyword callers; keyword-only breaks positional callers."
    )


@pytest.mark.parametrize("name", sorted(RELEASED_POSITIONAL))
def test_everything_added_since_the_release_is_keyword_only(name):
    """Parameters added after v2.2.3 must be keyword-only, so they can never shift a released one.

    This is what makes the guard above stable over time: with every addition keyword-only, the
    positional list is frozen by construction and future growth cannot reorder it.
    """
    func, expected = RELEASED_POSITIONAL[name]
    params = inspect.signature(func).parameters
    added = [n for n in params if n not in expected]
    not_keyword_only = [n for n in added if params[n].kind is not params[n].KEYWORD_ONLY]

    assert not not_keyword_only, (
        f"{name}: parameter(s) added since v2.2.3 are positionally bindable: {not_keyword_only}. "
        "Put them after a `*` marker."
    )
