"""Signature-guard tests for the released public entry points.

These pin the **positional** parameter order of every pipeline and of ``write_tiff_stack`` against
the last release, so a future parameter cannot be inserted mid-signature and silently re-bind every
argument after it.

That is not hypothetical. Commit 3bd2b07 (on ``next``, in no tag) inserted ``rebin_reduction``
immediately after ``rebin_by_tof`` in the three VENUS TOF pipelines and appended
``tiff_one_file_per_image``, shifting every later positional parameter — five of them in
``venus_tpx3_event``. ``write_tiff_stack`` likewise gained two positional parameters. Because none of
that had shipped, the fix was to make all four **keyword-only** rather than freeze the shift; these
guards now pin the v2.2.3 order and assert that everything added since is keyword-only.

**The expected lists below come from git tag v2.2.3, not from the code under test.** That matters: an
earlier version of this file was generated by introspecting the current signatures, so it pinned the
already-shifted order as "released" and could never have failed on the very regression it documents.
Regenerate these lists from the newest tag when a release happens, never from ``next``:

    git show v2.2.3:src/neunorm/pipelines/venus_tpx1.py

Appending a **keyword-only** parameter is always safe and needs no change here. Adding a positional
one, reordering, removing, or converting a released parameter to positional-only is a breaking change:
if a test fails, either revert it or treat it as a deliberate API break with a CHANGELOG entry.

Pattern follows ``test_rebin_tof_flexible.py::test_rebin_tof_preserves_legacy_positional_signature``,
which guards the leaf ``rebin_tof`` the same way.
"""

import inspect

import pytest

from neunorm.exporters.hdf5_writer import write_hdf5
from neunorm.exporters.tiff_writer import write_tiff_stack
from neunorm.filters.gamma_filter import apply_gamma_filter
from neunorm.loaders.event_loader import load_event_data, load_event_nexus
from neunorm.loaders.fits_loader import load_fits_stack
from neunorm.loaders.metadata_loader import load_metadata
from neunorm.loaders.stack_loader import load_stack
from neunorm.loaders.tiff_loader import load_tiff_stack
from neunorm.pipelines.mars_ccd import run_mars_ccd_pipeline
from neunorm.pipelines.mars_tpx3 import run_mars_tpx3_pipeline
from neunorm.pipelines.venus_ccd import run_venus_ccd_pipeline
from neunorm.pipelines.venus_tpx1 import run_venus_tpx1_pipeline
from neunorm.pipelines.venus_tpx3_event import run_venus_tpx3_event_pipeline
from neunorm.pipelines.venus_tpx3_histogram import run_venus_tpx3_histogram_pipeline
from neunorm.processing.normalizer import normalize_transmission, normalize_with_dark
from neunorm.processing.run_combiner import combine_runs
from neunorm.tof.event_converter import (
    convert_events_to_2d_histogram,
    convert_events_to_histogram,
)

# Positional order as released in v2.2.3. Sourced from the tag, NOT from the current code.
_VENUS_HISTOGRAM_V223 = [
    "sample_hdf5_paths",
    "ob_hdf5_paths",
    "sample_tiff_paths",
    "ob_tiff_paths",
    "output_path",
    "roi",
    "air_roi",
    "rebin_by_tof",
    "rebin_by_spatial",
    "flight_path",
]

RELEASED_POSITIONAL = {
    "run_venus_tpx1_pipeline": (run_venus_tpx1_pipeline, _VENUS_HISTOGRAM_V223),
    "run_venus_tpx3_histogram_pipeline": (run_venus_tpx3_histogram_pipeline, _VENUS_HISTOGRAM_V223),
    "run_venus_tpx3_event_pipeline": (
        run_venus_tpx3_event_pipeline,
        [
            "sample_paths",
            "ob_paths",
            "binning",
            "output_path",
            "roi",
            "air_roi",
            "rebin_by_tof",
            "rebin_by_spatial",
            "detector_shape",
            "event_id_offset",
            "bank_name",
            "flight_path",
        ],
    ),
    "run_venus_ccd_pipeline": (
        run_venus_ccd_pipeline,
        [
            "sample_paths",
            "ob_paths",
            "dark_paths",
            "output_path",
            "roi",
            "gamma_filter",
            "air_roi",
            "background_roi",
        ],
    ),
    "run_mars_ccd_pipeline": (
        run_mars_ccd_pipeline,
        [
            "sample_paths",
            "ob_paths",
            "dark_paths",
            "output_path",
            "roi",
            "gamma_filter",
            "background_roi",
        ],
    ),
    "run_mars_tpx3_pipeline": (
        run_mars_tpx3_pipeline,
        [
            "sample_paths",
            "ob_paths",
            "output_path",
            "roi",
            "gamma_filter",
            "detector_shape",
            "background_roi",
        ],
    ),
    "write_tiff_stack": (
        write_tiff_stack,
        ["output_path", "transmission", "metadata", "daqmetadata"],
    ),
    # Not pipelines, but released public entry points: every loader module below is published in
    # docs/api.rst with :members:. Each gained a keyword-only `progress` since v2.2.3, so their
    # positional lists are unchanged from the tag.
    "load_metadata": (
        load_metadata,
        ["file_path", "read_shutter_counts", "read_spectra_tof"],
    ),
    # `combine_runs` gained `metadata_match_atol` since v2.2.3, appended positionally. Nothing
    # released shifted (it went last), but it was the one addition the guard below could not see,
    # because this entry did not exist. It is keyword-only now, and guarded here.
    "combine_runs": (
        combine_runs,
        ["runs", "metadata_keys_to_sum", "metadata_check_match", "normalize_by_runs"],
    ),
    "load_stack": (load_stack, ["paths"]),
    "load_tiff_stack": (load_tiff_stack, ["paths", "tof_edges"]),
    "load_fits_stack": (load_fits_stack, ["paths", "tof_edges"]),
    "load_event_nexus": (
        load_event_nexus,
        ["file_path", "detector_bank", "detector_shape", "event_id_offset", "max_events"],
    ),
    "load_event_data": (load_event_data, ["file_path", "tof_clock", "max_events"]),
    "convert_events_to_histogram": (
        convert_events_to_histogram,
        [
            "events",
            "binning",
            "flight_path",
            "x_bins",
            "y_bins",
            "chunk_size",
            "compute_variance",
            "detector_time_offset",
        ],
    ),
    "convert_events_to_2d_histogram": (
        convert_events_to_2d_histogram,
        ["events", "detector_shape", "chunk_size"],
    ),
    "apply_gamma_filter": (
        apply_gamma_filter,
        ["data", "threshold_sigma", "kernel_size", "preserve_variance"],
    ),
    "write_hdf5": (
        write_hdf5,
        ["output_path", "transmission", "dead_pixel_mask", "hot_pixel_mask", "metadata"],
    ),
    "normalize_with_dark": (
        normalize_with_dark,
        [
            "sample",
            "ob",
            "dark",
            "proton_charge_sample",
            "proton_charge_ob",
            "pc_uncertainty",
            "background_roi",
            "background_roi_strict",
        ],
    ),
    "normalize_transmission": (
        normalize_transmission,
        [
            "sample",
            "ob",
            "proton_charge_sample",
            "proton_charge_ob",
            "pc_uncertainty",
            "background_roi",
            "background_roi_strict",
        ],
    ),
}


@pytest.mark.parametrize("name", sorted(RELEASED_POSITIONAL))
def test_positional_signature_matches_the_last_release_exactly(name):
    """The positional parameters must equal the v2.2.3 list — same names, same order, nothing extra.

    A full-list comparison, not a prefix: pinning only a prefix would miss a positional parameter
    appended after it, which still shifts nothing today but silently becomes load-bearing order the
    moment another is added. Anything new belongs after a ``*`` marker, where it never appears here.
    """
    func, expected = RELEASED_POSITIONAL[name]
    params = inspect.signature(func).parameters
    # The two kinds that actually participate in positional re-binding. Filtering by "not KEYWORD_ONLY"
    # instead would count `*args` and `**kwargs` as positional, so adding either to an entry point would
    # fail this guard for a reason it does not mean.
    positional_kinds = (inspect.Parameter.POSITIONAL_ONLY, inspect.Parameter.POSITIONAL_OR_KEYWORD)
    actual = [n for n, p in params.items() if p.kind in positional_kinds]

    assert actual == expected, (
        f"{name}: positional signature no longer matches the v2.2.3 release.\n"
        f"  released: {expected}\n"
        f"  current:  {actual}\n"
        "Add new parameters as keyword-only (after a `*` marker) instead of positionally."
    )


@pytest.mark.parametrize("name", sorted(RELEASED_POSITIONAL))
def test_released_parameters_remain_callable_by_keyword(name):
    """Every released parameter must still be bindable by name.

    Checks the parameter *kind*, not just the name: converting ``f(a, b)`` to ``f(a, /, b)`` keeps
    both names and both positions, passes an order comparison, and yet breaks every ``f(a=...)``
    caller. Making a released parameter keyword-only would equally break positional callers, and is
    caught by the order test above.
    """
    func, expected = RELEASED_POSITIONAL[name]
    params = inspect.signature(func).parameters

    missing = [n for n in expected if n not in params]
    assert not missing, f"{name}: released parameter(s) removed: {missing}"

    wrong_kind = {
        n: params[n].kind.description for n in expected if params[n].kind is not params[n].POSITIONAL_OR_KEYWORD
    }
    assert not wrong_kind, (
        f"{name}: released parameter(s) are no longer positional-or-keyword: {wrong_kind}. "
        "Positional-only breaks keyword callers; keyword-only breaks positional callers."
    )


@pytest.mark.parametrize("name", sorted(RELEASED_POSITIONAL))
def test_everything_added_since_the_release_is_keyword_only(name):
    """Parameters added after v2.2.3 must be keyword-only, so they can never shift a released one.

    This is what makes the guard above stable over time: with every addition keyword-only, the
    positional list is frozen by construction and future growth cannot reorder it.

    ``*args`` and ``**kwargs`` are exempt, for the same reason the positional guard above names the two
    positional kinds explicitly: neither can displace a released parameter, so failing on them would be
    a false positive rather than a caught break.
    """
    func, expected = RELEASED_POSITIONAL[name]
    params = inspect.signature(func).parameters
    added = [n for n in params if n not in expected]
    shiftable_kinds = (inspect.Parameter.POSITIONAL_ONLY, inspect.Parameter.POSITIONAL_OR_KEYWORD)
    positionally_bindable = [n for n in added if params[n].kind in shiftable_kinds]

    assert not positionally_bindable, (
        f"{name}: parameter(s) added since v2.2.3 are positionally bindable: {positionally_bindable}. "
        "Put them after a `*` marker."
    )
